---

- name: Report hv counts before template hack
  debug: msg="HV count is {{ num_xen_hosts }} XS, {{ num_kvm_hosts }} KVM, {{ num_esxi_hosts }} ESXi"

- name: create builtin xenserver template_dir
  file:
    path: "/acs/secondary/{{ env_name_clean }}/{{ env_name_clean }}-sec1/template/tmpl/1/5"
    state: directory
    mode: 0755
  when: num_xen_hosts | int > 0

- name: copy template and properties.template files
  get_url:
    url: "{{ templatehost }}/templates/builtin/{{ item }}"
    dest: "/acs/secondary/{{ env_name_clean }}/{{ env_name_clean }}-sec1/template/tmpl/1/5/{{ item }}"
  with_items:
    - "centos65-x86_64-xen.vhd.bz2"
#    - "template.properties"
  when: num_xen_hosts | int > 0

- name: create builtin kvm template_dir
  file:
    path: "/acs/secondary/{{ env_name_clean }}/{{ env_name_clean }}-sec1/template/tmpl/1/4"
    state: directory
    mode: 0755
  when: num_kvm_hosts | int > 0

- name: copy template and properties.template files
  get_url:
    url: "{{ templatehost }}/templates/builtin/{{ item }}"
    dest: "/acs/secondary/{{ env_name_clean }}/{{ env_name_clean }}-sec1/template/tmpl/1/4/{{ item }}"
  with_items:
    - "centos65-x86_64-kvm.qcow2.bz2"
#   - "template.properties"
  when: num_kvm_hosts | int > 0

- name: create builtin esxi template_dir
  file:
    path: "/acs/secondary/{{ env_name_clean }}/{{ env_name_clean }}-sec1/template/tmpl/1/7"
    state: directory
    mode: 0755
  when: num_esxi_hosts | int > 0

- name: copy template and properties.template files
  get_url:
    url: "{{ templatehost }}/templates/builtin/{{ item }}"
    dest: "/acs/secondary/{{ env_name_clean }}/{{ env_name_clean }}-sec1/template/tmpl/1/7/{{ item }}"
  with_items:
    - "centos65-x86_64-vmware.ova"
#    - "template.properties"
  when: num_esxi_hosts | int > 0
